### ISSUE TITLE
Separate parser from objects

### ISSUE THREAD

**Issue by jhoek** [dynasist/ALObjectParser#3]
Can I suggest that we make the ALObjectParser a separate, static and stateless class (ALObjectParser)? The only thing it should do, as far as I'm concerned, is something like this:

```csharp
static IEnumerable<ALObject> Read(string path)
```

I chose an IEnumerable as the return value type since a file could contain >1 object. For writing, I think we need the mirrored version, again in a separate, static and stateless class (ALObjectWriter?)

```csharp
static void Write(IEnumerable<ALObject> objects, string path)
```

**Comment by martonsagi** [comment]
I've been thinking myself to refactor the parsing using the Reader/Writer pattern.

I can imagine the new classes as this:

* static class ALObjectParser with Read/Write methods that internally would use
  * class ALObjectReaderBase
  * class ALObjectWriterBase

Perhaps generic methods, like `Read<T>(...): where T: ALObjectReaderBase` would also be useful, so you could replace the built-in reader/writer classes when needed.


> I chose an IEnumerable as the return value type since a file could contain >1 object.

I know it's technically possible to have more than one AL object per file, however, I'm strongly opposed to the idea of it. Anyway, agree on the part to at least handle the possibility.

**Comment by jhoek** [comment]
Sounds great! I'm also not a fan of >1 AL object in a file, but since it is technically possible, I think a parser should support it?

**Comment by martonsagi** [comment]
Separation is mostly done, parser handles more than one object per file. More unit tests are needed for confirmation. :)

I have renamed the static class to `ALParser` since the original classname was the same as namespace, which is confusing.

**Comment by lvanvugt** [comment]
> Separation is mostly done, parser handles more than one object per file. More unit tests are needed for confirmation. :)

Can I be of help?

**Comment by martonsagi** [comment]
In the testing? Sure! I'm finished with refactoring and updated all of the previous unit tests as well.
If you have more test cases, I'd appreciate them :)
